location = "local-1"
initial_leader = 1
local_deployment = true
optimize = OPTIMIZE
optimize_threshold = 0.97

[cluster_config]
configuration_id = 1
nodes = [1, 2, 3]
flexible_quorum = { read_quorum_size = 2, write_quorum_size = 2 }

[server_config]
pid = 1
election_tick_timeout = 1
resend_message_tick_timeout = 5
flush_batch_tick_timeout = 200
